language: node_js
node_js:
  - "7"
  - "6"
branches:
  only: 
    - master
env:
  - CXX=g++-4.8
  - BUILD_SCRIPT=/config/scripts/build.sh
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: chmod a+x $BUILD_SCRIPT && ./$BUILD_SCRIPT