environment:
  matrix:
    - nodejs_version: "7"

platform:
  - x64

install:
  - cinst yarn
  - cmd: npm i npm@latest-4 -g
  - ps: npm install --global --production windows-build-tools
  - cmd: yarn global add yo

before_build:
  - node --version && npm --version && yarn --version && yo --version && python --version

build_script:
  - yarn

test_script:
  - yarn run test