shallow_clone: true

environment:
  matrix:
    - nodejs_version: "7"

platform:
  - x64

install:
  - cinst yarn
  - cinst googlechrome
  - cmd: npm i npm@latest-4 -g
  - ps: npm install --global --production windows-build-tools
  - cmd: yarn global add yo
  # installing selenium-standalone
  - npm install -g selenium-standalone
  - selenium-standalone install
  # opening firewall ports
  - netsh advfirewall firewall add rule name="SeleniumIn" dir=in action=allow protocol=TCP localport=4441
  - netsh advfirewall firewall add rule name="SeleniumOut" dir=out action=allow protocol=TCP localport=4441
  # running selenium-standalone as background job
  - ps: Start-Process selenium-standalone 'start','--','-Djna.nosys=true'

before_build:
  - node --version && npm --version && yarn --version && yo --version && python --version

build_script:
  - yarn

test_script:
  - yarn run test